export const Products = [
  {
    id: 1,
    title: 'apple',
    category: 'fruits',
    price: '20.99',
    tags: 'fruits apple red royal gala fresh',
  },
  {
    id: 2,
    title: 'banana',
    category: 'fruits',
    price: '15.4',
    tags: 'fruits apple red royal gala fresh',
  },
  {
    id: 3,
    title: 'carrots',
    category: 'vegetables',
    price: '9.80',
    tags: 'vegetables carrots kilo small fresh',
  },
  {
    id: 4,
    title: 'dates',
    category: 'dry fruits',
    price: '55.4',
    tags: 'dry fruits nuts healthy snack pack fresh',
  },
  {
    id: 5,
    title: 'egg',
    category: 'poultry',
    price: '35.4',
    tags: 'pack 24 12 4 12 poultry eggs fresh',
  },
  {
    id: 6,
    title: 'fish',
    category: 'sea food',
    price: '55.4',
    tags: 'fish sea food salmon siamese pack frozen fresh',
  },
  {
    id: 7,
    title: 'digestive',
    category: 'snacks',
    price: '25.4',
    tags: 'cookies kids favorite digestive sugar snacks',
  },
  {
    id: 8,
    title: 'meat balls',
    category: 'meat',
    price: '45.9',
    tags: 'meat beef ready food pack frozen balls',
  },
  {
    id: 9,
    title: 'meat mince',
    category: 'meat',
    price: '89.9',
    tags: 'meat mince beef ready food pack frozen',
  },
  {
    id: 10,
    title: 'cashews',
    category: 'dry fruits',
    price: '85.9',
    tags: 'healthy snack fruits dry cashews',
  },
  {
    id: 11,
    title: 'chicken',
    category: 'chicken',
    price: '49.9',
    tags: 'chicken bone boneless frozen',
  },
  {
    id: 12,
    title: 'chicken bone less',
    category: 'meat',
    price: '49.9',
    tags: 'chicken bone boneless frozen',
  },
  {
    id: 13,
    title: 'chicken with bone',
    category: 'meat',
    price: '99.9',
    tags: 'chicken bone bone frozen',
  },
  {
    id: 14,
    title: 'coke',
    category: 'soft drinks',
    price: '19.2',
    tags: 'coke drinks soft cola diet',
  },
  {
    id: 15,
    title: 'pepsi',
    category: 'soft drinks',
    price: '19.9',
    tags: 'pepsi drinks soft cola diet',
  },
  {
    id: 14,
    title: 'juice',
    category: 'soft drinks',
    price: '19.2',
    tags: 'juice drinks soft fruit',
  },
  {
    id: 15,
    title: 'chips',
    category: 'snacks',
    price: '15.2',
    tags: 'snacks chips potato',
  },
  {
    id: 16,
    title: 'chocolate',
    category: 'snacks',
    price: '15.2',
    tags: 'snacks chips potato',
  },
];
