export const Products = [
  {
    id: 1,
    title: 'apple',
    category: 'fruits',
    price: '20.99',
    tags: 'fruits apple red royal gala fresh',
  },
  {
    id: 2,
    title: 'banana',
    category: 'fruits',
    price: '15.4',
    tags: 'fruits apple red royal gala fresh',
  },
  {
    id: 3,
    title: 'carrots',
    category: 'vegetables',
    price: '9.80',
    tags: 'vegetables carrots kilo small fresh',
  },
  {
    id: 4,
    title: 'dates',
    category: 'dry fruits',
    price: '55.4',
    tags: 'dry fruits nuts healthy pack fresh',
  },
  {
    id: 5,
    title: 'egg',
    category: 'poultry',
    price: '35.4',
    tags: 'pack 24 12 4 12 poultry eggs fresh',
  },
  {
    id: 6,
    title: 'fish',
    category: 'sea food',
    price: '55.4',
    tags: 'fish sea food salmon siamese pack frozen fresh',
  },
  {
    id: 7,
    title: 'digestive',
    category: 'cookies',
    price: '25.4',
    tags: 'cookies kids favorite digestive sugar snacks',
  },
  {
    id: 8,
    title: 'meat balls',
    category: 'meat',
    price: '45.9',
    tags: 'meat beef ready food pack frozen balls',
  },
  {
    id: 9,
    title: 'meat mince',
    category: 'meat',
    price: '89.9',
    tags: 'meat mince beef ready food pack frozen',
  },
  {
    id: 10,
    title: 'cashews',
    category: 'dry fruits',
    price: '85.9',
    tags: 'healthy snack fruits dry cashews',
  },
];
